### ISSUE TITLE
How to change the polyline color in a MapItemsControl?

### ISSUE THREAD

**Issue by UxxHans** [ClemensFischer/XAML-Map-Control#125]
I managed to add polylines, points, and pins into the map by binding the data in viewmodels.
But I couldn't change the line color in MapItemsControl.
```
            <mpc:MapItemsControl
                x:Name="PolylinesCollection"
                ItemContainerStyle="{StaticResource PolylineStyle}"
                ItemsSource="{Binding Polylines}"
                SelectionChanged="MapElementSelectionChanged"
                SelectionMode="Single" />
```
Here is the polyline collection.
```
            <Style x:Key="PolylineStyle" TargetType="mpc:MapItem">
                <EventSetter Event="TouchDown" Handler="MapElementSelection" />
                <Setter Property="AutoCollapse" Value="True" />
                <Setter Property="Opacity" Value="0.35" />
            </Style>
```
I created a "PolylineStyle" but I could only modify the opacity. How can I change the line color? Setting the foreground color didn't work. If someone knows please help me, much appreciated!

**Comment by ClemensFischer** [comment]
It is not clear what `Polylines`, i.e. the ItemsSource collection actually is, but assuming it is a collection of MapPolyline, you would have to set their `Stroke` and optionally `StrokeThickness` property.

Otherwise take a look at the sample application how polylines are drawn in an ItemsControl by means of a DataTemplate.
