### ISSUE TITLE
Zoom Scaling of Drawings

### ISSUE THREAD

**Issue by evbo** [ClemensFischer/XAML-Map-Control#65]
I see MapProjection has conversions for `x,y` to `lat,lon` (`Location`) but what about for Geometry dimensions such as `RadiusX,RadiusY`? Do I need to transform my NetTopologySuite UTM Geometry into WKS84 and then get the radius from it in that projection and use that for my binding?

Also, I notice the ellipse shape gets larger as you zoom out and smaller as you zoom in. Is there anyway to fix it to an absolute size so that no matter what zoom level it is always the same size relative to map features? In other words, if I draw an ellipse around a lake, whether I'm zoomed all the way in or all the way out, how can that ellipse stay perfectly in the same scale so it traces the perimeter of the lake?

**Comment by ClemensFischer** [comment]
MapProjection only transforms points or rectangular bounds, no complex geometries. Not sure which kind of geometry you are referring to, but since you talk about radius, use it with a MapPath as that with an EllipseGeometry in the example application.

If you declare an Ellipse and simply set the MapPanel.Location attached property, it will not be scaled. Or use a Pushpin with an appropriate Template. Or take a look at the Paths in the example's PointItemStyle.
