### ISSUE TITLE
Ability to change TileSize

### ISSUE THREAD

**Issue by varadero** [ClemensFischer/XAML-Map-Control#87]
Currently, the `TileSize` in `MapTileLayer` is defined as constant equal to 256:

https://github.com/ClemensFischer/XAML-Map-Control/blob/master/MapControl/Shared/MapTileLayer.cs#L29

```cs
    public class MapTileLayer : MapTileLayerBase
    {
        public const int TileSize = 256;
```

We have tiles with size 1024. If I manually change the constant to 1024 then the map looks correct. I can simply copy/paste the code in `MapTileLayer` to my class and set this tile size to whatever I want, but are there plans to allow this to be configurable by the caller ?

**Comment by ClemensFischer** [comment]
Be aware that the OpenStreetMap and Bing Maps tiling scheme imposes a fixed relationship between the tile size, the zoom level and the overall map size. A tile size other than 256 would break the calculation of the map boundaries, which you would notice when wrapping around at longitudes +/-180°.

How do your 1024x1024 tiles fit into this scheme? Is the topmost tile supposed to cover zoom level 2 instead of 0?

You may want to expose your map provider as a Web Map Tile Service (WMTS), which offers support for tile sizes other than 256.

**Comment by varadero** [comment]
My tiles are for Germany only. There is no tile 0/0/0 - but it has 1/0/0 which looks like this:

![image](https://user-images.githubusercontent.com/7610713/164433988-bd796616-3486-4b75-9c79-44011db98980.png)


Another tile - western German border 8/33/21 :

![image](https://user-images.githubusercontent.com/7610713/164434144-df15ec0e-7a01-4faa-86ac-2e3a5e143a68.png)

**Comment by ClemensFischer** [comment]
Instead of changing the TileSize value, add the following to MapTileLayer.cs, line 168, and set ZoomLevelOffset to -2. 

    public double ZoomLevelOffset { get; set; }

    private bool SetTileMatrix()
    {
        var tileMatrixZoomLevel = (int)Math.Floor(ParentMap.ZoomLevel + ZoomLevelOffset + 0.001); // avoid rounding issues
        ...

**Comment by okrasniuk** [comment]
ZoomLevelOffset seems works pretty good when we talking just about map rendering. But in this case operations like maptoviewcontrol and vice versa don't work. Even in SampleApps mouse pointer coordinate is absolutely incorrect in this case. But all perfect with changing TileSize.
