### ISSUE TITLE
Question : How to get BoundingBox for each zoom level ?

### ISSUE THREAD

**Issue by ronak-k-p** [ClemensFischer/XAML-Map-Control#97]
How can i get final bounding box before zoom applied?
I have requirement of perform certain checks on lat & long before applying zoom, I want to get boundingbox for next zoom level before its applied to map.

for current applied zoom level i know we can get bounding box by writing,
`var bindingBox= ViewRectToBoundingBox(new Rect(RenderSize));`

But consider currently i am at zoomlevel=3, but i want to determine bindingbox at zoomlevel 4.

**Comment by ClemensFischer** [comment]
There is no general answer to this question, because the bounding box depends on the map projection and the geodetic location of the zoom center. The map scale is however proportional to `Math.Pow(2d, zoomLevel)`, so if you zoom in by one level, the covered area has half width and height in projected coordinates.
